In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

ModuleNotFoundError: No module named 'numpy'

In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 1.5 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,"pg"])
print(arr)

['1' '2' '3' '4' '5' 'pg']


In [15]:
print(arr.dtype)

<U21


In [20]:
print(np.random.randint(1,1000,(3, 4)))

[[777 188 600 354]
 [366 616 683 417]
 [805 277 599 628]]
